apiVersion: v1
kind: ConfigMap
metadata:
  name: storm-config
  namespace: storm
data:
  NATS_URL: "nats://nats:4222"
  GATEWAY_ADDR: ":8080"
  MESSAGES_ADDR: ":8081"
  PPROF_ADDR_GATEWAY: ":6060"
  PPROF_ADDR_MESSAGES: ":6061"
  SUBJECT: "storm.events"
  CORS_ORIGIN: "http://localhost:5173"
