apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storm

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - nats.yaml
  - postgres.yaml
  - redis.yaml
  - gateway.yaml
  - messages.yaml
  - prometheus.yaml
  - grafana.yaml
  - ingress.yaml

images:
  - name: storm-gateway
    newName: storm-gateway
    newTag: latest
  - name: storm-messages
    newName: storm-messages
    newTag: latest
