apiVersion: v1
kind: ServiceAccount
metadata:
  name: storm-sa
  namespace: storm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: storm-readonly
  namespace: storm
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints","configmaps","secrets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storm-readonly-binding
  namespace: storm
subjects:
  - kind: ServiceAccount
    name: storm-sa
    namespace: storm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: storm-readonly
