apiVersion: v1
kind: Secret
metadata:
  name: storm-secret
  namespace: storm
type: Opaque
stringData:
  JWT_SECRET: "dev-secret"
  JWT_REFRESH_SECRET: "dev-secret"
  POSTGRES_DSN: "postgres://storm:storm@postgres:5432/storm?sslmode=disable"
  REDIS_ADDR: "redis:6379"
